#!/bin/bash

echo $GOPATH | grep ":"
if [[ $? == 0 ]];then
    GOPATH=${GOPATH//\\//}
    GOPATH=${GOPATH//:/}
    export GOPATH="/$GOPATH"
    echo $GOPATH
fi

export http_proxy=socks5://127.0.0.1:1080
export https_proxy=socks5://127.0.0.1:1080

go get $*